version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
    working_directory: /redis_cluster
    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-{{ checksum "Gemfile.lock" }}
            - vendor
      - run: bundle install --deployment
      - save_cache:
          paths: [vendor]
          key: vendor-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          key: 'redis-3.2.8'
      - run: .circleci/install.sh
      - save_cache:
          paths: [/bin/redis-server]
          key: "redis-3.2.8"

      - run: rake

